GO

/****** Object:  Index [IX_Producer_SchemeId]    Script Date: 10/12/2015 16:39:00 ******/
CREATE NONCLUSTERED INDEX [IX_Producer_SchemeId] ON [Producer].[Producer] 
(
	[SchemeId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


