//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Web.Areas.Admin.Views.RemovePCSRecords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Weee.Web.Areas.Admin.Views.RemovePCSRecords.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval number.
        /// </summary>
        public static string ApprovalNumber {
            get {
                return ResourceManager.GetString("ApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PCS records displayed have exceeded the 7-year retention period and are now available for deletion from WEEE Online..
        /// </summary>
        public static string BodyTextDesc1 {
            get {
                return ResourceManager.GetString("BodyTextDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PCS information to be deleted from both the internal and external services include:.
        /// </summary>
        public static string BodyTextDesc2 {
            get {
                return ResourceManager.GetString("BodyTextDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon clicking &apos;Delete&apos; you will be asked if you wish to confirm the deletion.
        /// </summary>
        public static string BodyTextDesc3 {
            get {
                return ResourceManager.GetString("BodyTextDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance year.
        /// </summary>
        public static string ComplianceYear {
            get {
                return ResourceManager.GetString("ComplianceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PCS records.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS name.
        /// </summary>
        public static string PCSName {
            get {
                return ResourceManager.GetString("PCSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table shows the PCS records for the selected year and scheme..
        /// </summary>
        public static string TableCaption {
            get {
                return ResourceManager.GetString("TableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove PCS records.
        /// </summary>
        public static string Titile {
            get {
                return ResourceManager.GetString("Titile", resourceCulture);
            }
        }
    }
}
