//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EA.Weee.Xml.MemberUpload {
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    [XmlRoot("scheme", Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema", IsNullable=false)]
    public partial class schemeType {
        
        private string approvalNoField;
        
        private string complianceYearField;
        
        private string tradingNameField;
        
        private schemeBusinessType schemeBusinessField;
        
        private producerType[] producerListField;
        
       
        /// <remarks/>
        public string approvalNo {
            get {
                return this.approvalNoField;
            }
            set {
                this.approvalNoField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="positiveInteger")]
        public string complianceYear {
            get {
                return this.complianceYearField;
            }
            set {
                this.complianceYearField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string tradingName {
            get {
                return this.tradingNameField;
            }
            set {
                this.tradingNameField = value;
            }
        }
        
        /// <remarks/>
        public schemeBusinessType schemeBusiness {
            get {
                return this.schemeBusinessField;
            }
            set {
                this.schemeBusinessField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("producer", IsNullable=false)]
        public producerType[] producerList {
            get {
                return this.producerListField;
            }
            set {
                this.producerListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class schemeBusinessType {
        
        private object itemField;
        
        /// <remarks/>
        [XmlElement("company", typeof(schemeCompanyType))]
        [XmlElement("partnership", typeof(schemePartnershipType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class schemeCompanyType {
        
        private string companyNameField;
        
        private string companyNumberField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string companyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class overseasProducerType {
        
        private string overseasProducerNameField;
        
        private contactDetailsType overseasContactField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string overseasProducerName {
            get {
                return this.overseasProducerNameField;
            }
            set {
                this.overseasProducerNameField = value;
            }
        }
        
        /// <remarks/>
        public contactDetailsType overseasContact {
            get {
                return this.overseasContactField;
            }
            set {
                this.overseasContactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class contactDetailsType {
        
        private string titleField;
        
        private string forenameField;
        
        private string surnameField;
        
        private string phoneLandLineField;
        
        private string phoneMobileField;
        
        private string faxField;
        
        private string emailField;
        
        private addressType addressField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string forename {
            get {
                return this.forenameField;
            }
            set {
                this.forenameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string phoneLandLine {
            get {
                return this.phoneLandLineField;
            }
            set {
                this.phoneLandLineField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string phoneMobile {
            get {
                return this.phoneMobileField;
            }
            set {
                this.phoneMobileField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public addressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class addressType {
        
        private string primaryNameField;
        
        private string secondaryNameField;
        
        private string streetNameField;
        
        private string townField;
        
        private string localityField;
        
        private string administrativeAreaField;
        
        private countryType countryField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string primaryName {
            get {
                return this.primaryNameField;
            }
            set {
                this.primaryNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string secondaryName {
            get {
                return this.secondaryNameField;
            }
            set {
                this.secondaryNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string streetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string administrativeArea {
            get {
                return this.administrativeAreaField;
            }
            set {
                this.administrativeAreaField = value;
            }
        }
        
        /// <remarks/>
        public countryType country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("internationalPostCode", typeof(string))]
        [XmlElement("postCode", typeof(string))]
        [XmlChoiceIdentifier("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public enum countryType {
        
        /// <remarks/>
        [XmlEnum("UK - ENGLAND")]
        UKENGLAND,
        
        /// <remarks/>
        [XmlEnum("UK - SCOTLAND")]
        UKSCOTLAND,
        
        /// <remarks/>
        [XmlEnum("UK - WALES")]
        UKWALES,
        
        /// <remarks/>
        [XmlEnum("UK - NORTHERN IRELAND")]
        UKNORTHERNIRELAND,
        
        /// <remarks/>
        [XmlEnum("ISLE OF MAN")]
        ISLEOFMAN,
        
        /// <remarks/>
        GUERNSEY,
        
        /// <remarks/>
        AFGHANISTAN,
        
        /// <remarks/>
        [XmlEnum("ÅLAND ISLANDS")]
        ÅLANDISLANDS,
        
        /// <remarks/>
        ALBANIA,
        
        /// <remarks/>
        ALGERIA,
        
        /// <remarks/>
        [XmlEnum("AMERICAN SAMOA")]
        AMERICANSAMOA,
        
        /// <remarks/>
        ANDORRA,
        
        /// <remarks/>
        ANGOLA,
        
        /// <remarks/>
        ANGUILLA,
        
        /// <remarks/>
        ANTARCTICA,
        
        /// <remarks/>
        [XmlEnum("ANTIGUA AND BARBUDA")]
        ANTIGUAANDBARBUDA,
        
        /// <remarks/>
        ARGENTINA,
        
        /// <remarks/>
        ARMENIA,
        
        /// <remarks/>
        ARUBA,
        
        /// <remarks/>
        AUSTRALIA,
        
        /// <remarks/>
        AUSTRIA,
        
        /// <remarks/>
        AZERBAIJAN,
        
        /// <remarks/>
        BAHAMAS,
        
        /// <remarks/>
        BAHRAIN,
        
        /// <remarks/>
        BANGLADESH,
        
        /// <remarks/>
        BARBADOS,
        
        /// <remarks/>
        BELARUS,
        
        /// <remarks/>
        BELGIUM,
        
        /// <remarks/>
        BELIZE,
        
        /// <remarks/>
        BENIN,
        
        /// <remarks/>
        BERMUDA,
        
        /// <remarks/>
        BHUTAN,
        
        /// <remarks/>
        BOLIVIA,
        
        /// <remarks/>
        [XmlEnum("BONAIRE, SINT EUSTATIUS AND SABA")]
        BONAIRESINTEUSTATIUSANDSABA,
        
        /// <remarks/>
        [XmlEnum("BOSNIA AND HERZEGOVINA")]
        BOSNIAANDHERZEGOVINA,
        
        /// <remarks/>
        BOTSWANA,
        
        /// <remarks/>
        [XmlEnum("BOUVET ISLAND")]
        BOUVETISLAND,
        
        /// <remarks/>
        BRAZIL,
        
        /// <remarks/>
        [XmlEnum("BRITISH INDIAN OCEAN TERRITORY")]
        BRITISHINDIANOCEANTERRITORY,
        
        /// <remarks/>
        [XmlEnum("BRUNEI DARUSSALAM")]
        BRUNEIDARUSSALAM,
        
        /// <remarks/>
        BULGARIA,
        
        /// <remarks/>
        [XmlEnum("BURKINA FASO")]
        BURKINAFASO,
        
        /// <remarks/>
        BURUNDI,
        
        /// <remarks/>
        [XmlEnum("CABO VERDE")]
        CABOVERDE,
        
        /// <remarks/>
        CAMBODIA,
        
        /// <remarks/>
        CAMEROON,
        
        /// <remarks/>
        CANADA,
        
        /// <remarks/>
        [XmlEnum("CAYMAN ISLANDS")]
        CAYMANISLANDS,
        
        /// <remarks/>
        [XmlEnum("CENTRAL AFRICAN REPUBLIC")]
        CENTRALAFRICANREPUBLIC,
        
        /// <remarks/>
        CHAD,
        
        /// <remarks/>
        CHILE,
        
        /// <remarks/>
        CHINA,
        
        /// <remarks/>
        [XmlEnum("CHRISTMAS ISLAND")]
        CHRISTMASISLAND,
        
        /// <remarks/>
        [XmlEnum("COCOS (KEELING) ISLANDS")]
        COCOSKEELINGISLANDS,
        
        /// <remarks/>
        COLOMBIA,
        
        /// <remarks/>
        COMOROS,
        
        /// <remarks/>
        CONGO,
        
        /// <remarks/>
        [XmlEnum("CONGO, DEMOCRATIC REPUBLIC OF")]
        CONGODEMOCRATICREPUBLICOF,
        
        /// <remarks/>
        [XmlEnum("COOK ISLANDS")]
        COOKISLANDS,
        
        /// <remarks/>
        [XmlEnum("COSTA RICA")]
        COSTARICA,
        
        /// <remarks/>
        [XmlEnum("CÔTE D\'IVOIRE")]
        CÔTEDIVOIRE,
        
        /// <remarks/>
        CROATIA,
        
        /// <remarks/>
        CUBA,
        
        /// <remarks/>
        CURAÇAO,
        
        /// <remarks/>
        CYPRUS,
        
        /// <remarks/>
        [XmlEnum("CZECH REPUBLIC")]
        CZECHREPUBLIC,
        
        /// <remarks/>
        DENMARK,
        
        /// <remarks/>
        DJIBOUTI,
        
        /// <remarks/>
        DOMINICA,
        
        /// <remarks/>
        [XmlEnum("DOMINICAN REPUBLIC")]
        DOMINICANREPUBLIC,
        
        /// <remarks/>
        ECUADOR,
        
        /// <remarks/>
        EGYPT,
        
        /// <remarks/>
        [XmlEnum("EL SALVADOR")]
        ELSALVADOR,
        
        /// <remarks/>
        [XmlEnum("EQUATORIAL GUINEA")]
        EQUATORIALGUINEA,
        
        /// <remarks/>
        ERITREA,
        
        /// <remarks/>
        ESTONIA,
        
        /// <remarks/>
        ETHIOPIA,
        
        /// <remarks/>
        [XmlEnum("FALKLAND ISLANDS, THE MALVINAS")]
        FALKLANDISLANDSTHEMALVINAS,
        
        /// <remarks/>
        [XmlEnum("FAROE ISLANDS")]
        FAROEISLANDS,
        
        /// <remarks/>
        FIJI,
        
        /// <remarks/>
        FINLAND,
        
        /// <remarks/>
        FRANCE,
        
        /// <remarks/>
        [XmlEnum("FRENCH GUIANA")]
        FRENCHGUIANA,
        
        /// <remarks/>
        [XmlEnum("FRENCH POLYNESIA")]
        FRENCHPOLYNESIA,
        
        /// <remarks/>
        [XmlEnum("FRENCH SOUTHERN TERRITORIES")]
        FRENCHSOUTHERNTERRITORIES,
        
        /// <remarks/>
        GABON,
        
        /// <remarks/>
        GAMBIA,
        
        /// <remarks/>
        GEORGIA,
        
        /// <remarks/>
        GERMANY,
        
        /// <remarks/>
        GHANA,
        
        /// <remarks/>
        GIBRALTAR,
        
        /// <remarks/>
        GREECE,
        
        /// <remarks/>
        GREENLAND,
        
        /// <remarks/>
        GRENADA,
        
        /// <remarks/>
        GUADELOUPE,
        
        /// <remarks/>
        GUAM,
        
        /// <remarks/>
        GUATEMALA,
        
        /// <remarks/>
        GUINEA,
        
        /// <remarks/>
        [XmlEnum("GUINEA-BISSAU")]
        GUINEABISSAU,
        
        /// <remarks/>
        GUYANA,
        
        /// <remarks/>
        HAITI,
        
        /// <remarks/>
        [XmlEnum("HEARD ISLAND AND MCDONALD ISLANDS")]
        HEARDISLANDANDMCDONALDISLANDS,
        
        /// <remarks/>
        [XmlEnum("HOLY SEE")]
        HOLYSEE,
        
        /// <remarks/>
        HONDURAS,
        
        /// <remarks/>
        [XmlEnum("HONG KONG")]
        HONGKONG,
        
        /// <remarks/>
        HUNGARY,
        
        /// <remarks/>
        ICELAND,
        
        /// <remarks/>
        INDIA,
        
        /// <remarks/>
        INDONESIA,
        
        /// <remarks/>
        [XmlEnum("IRAN, ISLAMIC REPUBLIC OF")]
        IRANISLAMICREPUBLICOF,
        
        /// <remarks/>
        IRAQ,
        
        /// <remarks/>
        IRELAND,
        
        /// <remarks/>
        ISRAEL,
        
        /// <remarks/>
        ITALY,
        
        /// <remarks/>
        JAMAICA,
        
        /// <remarks/>
        JAPAN,
        
        /// <remarks/>
        JERSEY,
        
        /// <remarks/>
        JORDAN,
        
        /// <remarks/>
        KAZAKHSTAN,
        
        /// <remarks/>
        KENYA,
        
        /// <remarks/>
        KIRIBATI,
        
        /// <remarks/>
        [XmlEnum("KOREA, THE DEMOCRATIC PEOPLE\'S REPUBLIC OF")]
        KOREATHEDEMOCRATICPEOPLESREPUBLICOF,
        
        /// <remarks/>
        [XmlEnum("KOREA, THE REPUBLIC OF")]
        KOREATHEREPUBLICOF,
        
        /// <remarks/>
        KUWAIT,
        
        /// <remarks/>
        KYRGYZSTAN,
        
        /// <remarks/>
        [XmlEnum("LAO PEOPLE\'S DEMOCRATIC REPUBLIC")]
        LAOPEOPLESDEMOCRATICREPUBLIC,
        
        /// <remarks/>
        LATVIA,
        
        /// <remarks/>
        LEBANON,
        
        /// <remarks/>
        LESOTHO,
        
        /// <remarks/>
        LIBERIA,
        
        /// <remarks/>
        LIBYA,
        
        /// <remarks/>
        LIECHTENSTEIN,
        
        /// <remarks/>
        LITHUANIA,
        
        /// <remarks/>
        LUXEMBOURG,
        
        /// <remarks/>
        MACAU,
        
        /// <remarks/>
        [XmlEnum("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF")]
        MACEDONIATHEFORMERYUGOSLAVREPUBLICOF,
        
        /// <remarks/>
        MADAGASCAR,
        
        /// <remarks/>
        MALAWI,
        
        /// <remarks/>
        MALAYSIA,
        
        /// <remarks/>
        MALDIVES,
        
        /// <remarks/>
        MALI,
        
        /// <remarks/>
        MALTA,
        
        /// <remarks/>
        [XmlEnum("MARSHALL ISLANDS")]
        MARSHALLISLANDS,
        
        /// <remarks/>
        MARTINIQUE,
        
        /// <remarks/>
        MAURITANIA,
        
        /// <remarks/>
        MAURITIUS,
        
        /// <remarks/>
        MAYOTTE,
        
        /// <remarks/>
        MEXICO,
        
        /// <remarks/>
        [XmlEnum("MICRONESIA, FEDERATED STATES OF")]
        MICRONESIAFEDERATEDSTATESOF,
        
        /// <remarks/>
        MOLDOVA,
        
        /// <remarks/>
        MONACO,
        
        /// <remarks/>
        MONGOLIA,
        
        /// <remarks/>
        MONTENEGRO,
        
        /// <remarks/>
        MONTSERRAT,
        
        /// <remarks/>
        MOROCCO,
        
        /// <remarks/>
        MOZAMBIQUE,
        
        /// <remarks/>
        MYANMAR,
        
        /// <remarks/>
        NAMIBIA,
        
        /// <remarks/>
        NAURU,
        
        /// <remarks/>
        NEPAL,
        
        /// <remarks/>
        NETHERLANDS,
        
        /// <remarks/>
        [XmlEnum("NEW CALEDONIA")]
        NEWCALEDONIA,
        
        /// <remarks/>
        [XmlEnum("NEW ZEALAND")]
        NEWZEALAND,
        
        /// <remarks/>
        NICARAGUA,
        
        /// <remarks/>
        NIGER,
        
        /// <remarks/>
        NIGERIA,
        
        /// <remarks/>
        NIUE,
        
        /// <remarks/>
        [XmlEnum("NORFOLK ISLAND")]
        NORFOLKISLAND,
        
        /// <remarks/>
        [XmlEnum("NORTHERN MARIANA ISLANDS")]
        NORTHERNMARIANAISLANDS,
        
        /// <remarks/>
        NORWAY,
        
        /// <remarks/>
        OMAN,
        
        /// <remarks/>
        PAKISTAN,
        
        /// <remarks/>
        PALAU,
        
        /// <remarks/>
        [XmlEnum("PALESTINE, STATE OF")]
        PALESTINESTATEOF,
        
        /// <remarks/>
        PANAMA,
        
        /// <remarks/>
        [XmlEnum("PAPUA NEW GUINEA")]
        PAPUANEWGUINEA,
        
        /// <remarks/>
        PARAGUAY,
        
        /// <remarks/>
        PERU,
        
        /// <remarks/>
        PHILIPPINES,
        
        /// <remarks/>
        PITCAIRN,
        
        /// <remarks/>
        POLAND,
        
        /// <remarks/>
        PORTUGAL,
        
        /// <remarks/>
        [XmlEnum("PUERTO RICO")]
        PUERTORICO,
        
        /// <remarks/>
        QATAR,
        
        /// <remarks/>
        RÉUNION,
        
        /// <remarks/>
        ROMANIA,
        
        /// <remarks/>
        [XmlEnum("RUSSIAN FEDERATION")]
        RUSSIANFEDERATION,
        
        /// <remarks/>
        RWANDA,
        
        /// <remarks/>
        [XmlEnum("SAINT BARTHÉLEMY")]
        SAINTBARTHÉLEMY,
        
        /// <remarks/>
        [XmlEnum("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA")]
        SAINTHELENAASCENSIONANDTRISTANDACUNHA,
        
        /// <remarks/>
        [XmlEnum("SAINT KITTS AND NEVIS")]
        SAINTKITTSANDNEVIS,
        
        /// <remarks/>
        [XmlEnum("SAINT LUCIA")]
        SAINTLUCIA,
        
        /// <remarks/>
        [XmlEnum("SAINT PIERRE AND MIQUELON")]
        SAINTPIERREANDMIQUELON,
        
        /// <remarks/>
        [XmlEnum("SAINT VINCENT AND THE GRENADINES")]
        SAINTVINCENTANDTHEGRENADINES,
        
        /// <remarks/>
        [XmlEnum("SAINT-MARTIN (FRANCE)")]
        SAINTMARTINFRANCE,
        
        /// <remarks/>
        SAMOA,
        
        /// <remarks/>
        [XmlEnum("SAN MARINO")]
        SANMARINO,
        
        /// <remarks/>
        [XmlEnum("SAO TOME AND PRINCIPE")]
        SAOTOMEANDPRINCIPE,
        
        /// <remarks/>
        [XmlEnum("SAUDI ARABIA")]
        SAUDIARABIA,
        
        /// <remarks/>
        SENEGAL,
        
        /// <remarks/>
        SERBIA,
        
        /// <remarks/>
        SEYCHELLES,
        
        /// <remarks/>
        [XmlEnum("SIERRA LEONE")]
        SIERRALEONE,
        
        /// <remarks/>
        SINGAPORE,
        
        /// <remarks/>
        [XmlEnum("SINT MAARTEN (DUTCH PART)")]
        SINTMAARTENDUTCHPART,
        
        /// <remarks/>
        SLOVAKIA,
        
        /// <remarks/>
        SLOVENIA,
        
        /// <remarks/>
        [XmlEnum("SOLOMON ISLANDS")]
        SOLOMONISLANDS,
        
        /// <remarks/>
        SOMALIA,
        
        /// <remarks/>
        [XmlEnum("SOUTH AFRICA")]
        SOUTHAFRICA,
        
        /// <remarks/>
        [XmlEnum("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS")]
        SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS,
        
        /// <remarks/>
        [XmlEnum("SOUTH SUDAN")]
        SOUTHSUDAN,
        
        /// <remarks/>
        SPAIN,
        
        /// <remarks/>
        [XmlEnum("SRI LANKA")]
        SRILANKA,
        
        /// <remarks/>
        SUDAN,
        
        /// <remarks/>
        SURINAME,
        
        /// <remarks/>
        [XmlEnum("SVALBARD AND JAN MAYEN ISLANDS")]
        SVALBARDANDJANMAYENISLANDS,
        
        /// <remarks/>
        SWAZILAND,
        
        /// <remarks/>
        SWEDEN,
        
        /// <remarks/>
        SWITZERLAND,
        
        /// <remarks/>
        [XmlEnum("SYRIA ARAB REPUBLIC")]
        SYRIAARABREPUBLIC,
        
        /// <remarks/>
        [XmlEnum("TAIWAN (PROVINCE OF CHINA)")]
        TAIWANPROVINCEOFCHINA,
        
        /// <remarks/>
        TAJIKISTAN,
        
        /// <remarks/>
        [XmlEnum("TANZANIA, UNITED REPUBLIC OF")]
        TANZANIAUNITEDREPUBLICOF,
        
        /// <remarks/>
        THAILAND,
        
        /// <remarks/>
        [XmlEnum("TIMOR-LESTE")]
        TIMORLESTE,
        
        /// <remarks/>
        TOGO,
        
        /// <remarks/>
        TOKELAU,
        
        /// <remarks/>
        TONGA,
        
        /// <remarks/>
        [XmlEnum("TRINIDAD AND TOBAGO")]
        TRINIDADANDTOBAGO,
        
        /// <remarks/>
        TUNISIA,
        
        /// <remarks/>
        TURKEY,
        
        /// <remarks/>
        TURKMENISTAN,
        
        /// <remarks/>
        [XmlEnum("TURKS AND CAICOS ISLANDS")]
        TURKSANDCAICOSISLANDS,
        
        /// <remarks/>
        TUVALU,
        
        /// <remarks/>
        UGANDA,
        
        /// <remarks/>
        UKRAINE,
        
        /// <remarks/>
        [XmlEnum("UNITED ARAB EMIRATES")]
        UNITEDARABEMIRATES,
        
        /// <remarks/>
        [XmlEnum("UNITED STATES OF AMERICA")]
        UNITEDSTATESOFAMERICA,
        
        /// <remarks/>
        [XmlEnum("UNITED STATES MINOR OUTLYING ISLANDS")]
        UNITEDSTATESMINOROUTLYINGISLANDS,
        
        /// <remarks/>
        URUGUAY,
        
        /// <remarks/>
        UZBEKISTAN,
        
        /// <remarks/>
        VANUATU,
        
        /// <remarks/>
        [XmlEnum("VENEZUELA (BOLIVARIAN REPUBLIC OF)")]
        VENEZUELABOLIVARIANREPUBLICOF,
        
        /// <remarks/>
        [XmlEnum("VIET NAM")]
        VIETNAM,
        
        /// <remarks/>
        [XmlEnum("VIRGIN ISLANDS (BRITISH)")]
        VIRGINISLANDSBRITISH,
        
        /// <remarks/>
        [XmlEnum("VIRGIN ISLANDS (U.S.)")]
        VIRGINISLANDSUS,
        
        /// <remarks/>
        [XmlEnum("WALLIS AND FUTUNA")]
        WALLISANDFUTUNA,
        
        /// <remarks/>
        [XmlEnum("WESTERN SAHARA")]
        WESTERNSAHARA,
        
        /// <remarks/>
        YEMEN,
        
        /// <remarks/>
        ZAMBIA,
        
        /// <remarks/>
        ZIMBABWE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        internationalPostCode,
        
        /// <remarks/>
        postCode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class authorisedRepresentativeType {
        
        private overseasProducerType overseasProducerField;
        
        /// <remarks/>
        public overseasProducerType overseasProducer {
            get {
                return this.overseasProducerField;
            }
            set {
                this.overseasProducerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class companyType {
        
        private string companyNameField;
        
        private string companyNumberField;
        
        private contactDetailsContainerType registeredOfficeField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string companyNumber {
            get {
                return this.companyNumberField;
            }
            set {
                this.companyNumberField = value;
            }
        }
        
        /// <remarks/>
        public contactDetailsContainerType registeredOffice {
            get {
                return this.registeredOfficeField;
            }
            set {
                this.registeredOfficeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class contactDetailsContainerType {
        
        private contactDetailsType contactDetailsField;
        
        /// <remarks/>
        public contactDetailsType contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class partnershipType {
        
        private string partnershipNameField;
        
        private string[] partnershipListField;
        
        private contactDetailsContainerType principalPlaceOfBusinessField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string partnershipName {
            get {
                return this.partnershipNameField;
            }
            set {
                this.partnershipNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("partner", DataType="token", IsNullable=false)]
        public string[] partnershipList {
            get {
                return this.partnershipListField;
            }
            set {
                this.partnershipListField = value;
            }
        }
        
        /// <remarks/>
        public contactDetailsContainerType principalPlaceOfBusiness {
            get {
                return this.principalPlaceOfBusinessField;
            }
            set {
                this.principalPlaceOfBusinessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class optionalContactDetailsContainerType {
        
        private contactDetailsType contactDetailsField;
        
        /// <remarks/>
        public contactDetailsType contactDetails {
            get {
                return this.contactDetailsField;
            }
            set {
                this.contactDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class producerBusinessType {
        
        private optionalContactDetailsContainerType correspondentForNoticesField;
        
        private object itemField;
        
        /// <remarks/>
        public optionalContactDetailsContainerType correspondentForNotices {
            get {
                return this.correspondentForNoticesField;
            }
            set {
                this.correspondentForNoticesField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("company", typeof(companyType))]
        [XmlElement("partnership", typeof(partnershipType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class producerType {
        
        private statusType statusField;
        
        private string registrationNoField;
        
        private string tradingNameField;
        
        private string[] sICCodeListField;
        
        private bool vATRegisteredField;
        
        private annualTurnoverBandType annualTurnoverBandField;
        
        private eeePlacedOnMarketBandType eeePlacedOnMarketBandField;
        
        private obligationTypeType obligationTypeField;
        
        private string[] producerBrandNamesField;
        
        private producerBusinessType producerBusinessField;
        
        private authorisedRepresentativeType authorisedRepresentativeField;
        
        private System.DateTime ceaseToExistDateField;
        
        private bool ceaseToExistDateFieldSpecified;
        
        private sellingTechniqueType sellingTechniqueField;
        
        /// <remarks/>
        public statusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string registrationNo {
            get {
                return this.registrationNoField;
            }
            set {
                this.registrationNoField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string tradingName {
            get {
                return this.tradingNameField;
            }
            set {
                this.tradingNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("SICCode", DataType="token", IsNullable=false)]
        public string[] SICCodeList {
            get {
                return this.sICCodeListField;
            }
            set {
                this.sICCodeListField = value;
            }
        }
        
        /// <remarks/>
        public bool VATRegistered {
            get {
                return this.vATRegisteredField;
            }
            set {
                this.vATRegisteredField = value;
            }
        }
        
        /// <remarks/>
        public annualTurnoverBandType annualTurnoverBand {
            get {
                return this.annualTurnoverBandField;
            }
            set {
                this.annualTurnoverBandField = value;
            }
        }
        
        /// <remarks/>
        public eeePlacedOnMarketBandType eeePlacedOnMarketBand {
            get {
                return this.eeePlacedOnMarketBandField;
            }
            set {
                this.eeePlacedOnMarketBandField = value;
            }
        }
        
        /// <remarks/>
        public obligationTypeType obligationType {
            get {
                return this.obligationTypeField;
            }
            set {
                this.obligationTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("brandname", IsNullable=false)]
        public string[] producerBrandNames {
            get {
                return this.producerBrandNamesField;
            }
            set {
                this.producerBrandNamesField = value;
            }
        }
        
        /// <remarks/>
        public producerBusinessType producerBusiness {
            get {
                return this.producerBusinessField;
            }
            set {
                this.producerBusinessField = value;
            }
        }
        
        /// <remarks/>
        public authorisedRepresentativeType authorisedRepresentative {
            get {
                return this.authorisedRepresentativeField;
            }
            set {
                this.authorisedRepresentativeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="date")]
        public System.DateTime ceaseToExistDate {
            get {
                return this.ceaseToExistDateField;
            }
            set {
                this.ceaseToExistDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ceaseToExistDateSpecified {
            get {
                return this.ceaseToExistDateFieldSpecified;
            }
            set {
                this.ceaseToExistDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sellingTechniqueType sellingTechnique {
            get {
                return this.sellingTechniqueField;
            }
            set {
                this.sellingTechniqueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public enum statusType {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public enum annualTurnoverBandType {
        
        /// <remarks/>
        [XmlEnum("Less than or equal to one million pounds")]
        Lessthanorequaltoonemillionpounds,
        
        /// <remarks/>
        [XmlEnum("Greater than one million pounds")]
        Greaterthanonemillionpounds,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public enum eeePlacedOnMarketBandType {
        
        /// <remarks/>
        [XmlEnum("More than or equal to 5T EEE placed on market")]
        Morethanorequalto5TEEEplacedonmarket,
        
        /// <remarks/>
        [XmlEnum("Less than 5T EEE placed on market")]
        Lessthan5TEEEplacedonmarket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public enum obligationTypeType {
        
        /// <remarks/>
        B2B,
        
        /// <remarks/>
        B2C,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public enum sellingTechniqueType {
        
        /// <remarks/>
        [XmlEnum("Direct Selling to End User")]
        DirectSellingtoEndUser,
        
        /// <remarks/>
        [XmlEnum("Indirect Selling to End User")]
        IndirectSellingtoEndUser,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema")]
    public partial class schemePartnershipType {
        
        private string partnershipNameField;
        
        private string[] partnershipListField;
        
        /// <remarks/>
        [XmlElement(DataType="token")]
        public string partnershipName {
            get {
                return this.partnershipNameField;
            }
            set {
                this.partnershipNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("partner", DataType="token", IsNullable=false)]
        public string[] partnershipList {
            get {
                return this.partnershipListField;
            }
            set {
                this.partnershipListField = value;
            }
        }
    }
}
