ALTER TABLE [AATF].[WeeeSentOn] DROP COLUMN AATFReturnId
ALTER TABLE [AATF].[WeeeSentOn] DROP COLUMN SiteAddressId
ALTER TABLE [AATF].[WeeeSentOn] ADD ReturnId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE [AATF].[WeeeSentOn] ADD AatfId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE [AATF].[WeeeSentOn] ADD OperatorAddressId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE [AATF].[WeeeSentOn] ADD SiteAddressId UNIQUEIDENTIFIER NOT NULL
ALTER TABLE [AATF].[WeeeSentOn] ADD CONSTRAINT FK_WeeeReused_ReturnId FOREIGN KEY (ReturnId) REFERENCES [AATF].[Return](Id)
ALTER TABLE [AATF].[WeeeSentOn] ADD CONSTRAINT FK_WeeeReused_AatfId FOREIGN KEY (AatfId) REFERENCES [AATF].[AATF](Id)
ALTER TABLE [AATF].[WeeeSentOn] ADD CONSTRAINT FK_WeeeReused_OperatorAddressId FOREIGN KEY (OperatorAddressId) REFERENCES [AATF].[Address](Id)
ALTER TABLE [AATF].[WeeeSentOn] ADD CONSTRAINT FK_WeeeReused_SiteAddressId FOREIGN KEY (SiteAddressId) REFERENCES [AATF].[Address](Id)

ALTER TABLE [AATF].[WeeeSentOnAmount] DROP COLUMN ObligationType
ALTER TABLE [AATF].[WeeeSentOnAmount] DROP COLUMN Tonnage
ALTER TABLE [AATF].[WeeeSentOnAmount] ADD HouseholdTonnage decimal(28, 3)
ALTER TABLE [AATF].[WeeeSentOnAmount] ADD NonHouseholdTonnage decimal(28, 3)