BEGIN TRANSACTION
DELETE FROM [AATF].NonObligatedWeee
DELETE FROM [AATF].ReturnScheme
DELETE FROM [AATF].WeeeReceivedAmount
DELETE FROM [AATF].WeeeReceived
DELETE FROM [AATF].WeeeReusedAmount
DELETE FROM [AATF].WeeeReusedSite
DELETE FROM [AATF].WeeeReused
DELETE FROM [AATF].WeeeSentOn
DELETE FROM [AATF].WeeeSentOnAmount
DELETE FROM [AATF].AATFReturnReportOn
DELETE FROM [AATF].AATF
DELETE FROM [AATF].[Address]
DELETE FROM [AATF].[Return]
DELETE FROM [AATF].Operator
COMMIT TRANSACTION