ALTER TABLE [AATF].[AATF] ADD OperatorId UNIQUEIDENTIFIER NOT NULL;
ALTER TABLE [AATF].[AATF] ADD CONSTRAINT FK_AATFOperator_OperatorId FOREIGN KEY (OperatorId) REFERENCES [AATF].[Operator](Id);
IF (EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'AATF' 
                 AND  TABLE_NAME = 'OperatorAATF'))
BEGIN
	DROP TABLE [AATF].[OperatorAATF];
END