ALTER TABLE [AATF].[AATF] ALTER COLUMN ApprovalNumber NVARCHAR(10) NOT NULL;
ALTER TABLE [AATF].[AATF] ALTER COLUMN [Status] INT NOT NULL;
ALTER TABLE [AATF].[Operator] ADD CONSTRAINT UC_Operator_OrganisationId UNIQUE (OrganisationId);