//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EA.Weee.Xml.DataReturns {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns", IsNullable=false)]
    public partial class SchemeReturn {
        
        private string approvalNoField;
        
        private string complianceYearField;
        
        private SchemeReturnReturnPeriod returnPeriodField;
        
        private TonnageReturnType[] collectedFromDCFField;
        
        private SchemeReturnDeliveredToATF[] deliveredToATFField;
        
        private SchemeReturnDeliveredToAE[] deliveredToAEField;
        
        private TonnageReturnType[] b2CWEEEFromDistributorsField;
        
        private TonnageReturnType[] b2CWEEEFromFinalHoldersField;
        
        private SchemeReturnProducer[] producerListField;
        
        public SchemeReturn() {
        }
     
        /// <remarks/>
        public string ApprovalNo {
            get {
                return this.approvalNoField;
            }
            set {
                this.approvalNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string ComplianceYear {
            get {
                return this.complianceYearField;
            }
            set {
                this.complianceYearField = value;
            }
        }
        
        /// <remarks/>
        public SchemeReturnReturnPeriod ReturnPeriod {
            get {
                return this.returnPeriodField;
            }
            set {
                this.returnPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Return", IsNullable=false)]
        public TonnageReturnType[] CollectedFromDCF {
            get {
                return this.collectedFromDCFField;
            }
            set {
                this.collectedFromDCFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveredToATF")]
        public SchemeReturnDeliveredToATF[] DeliveredToATF {
            get {
                return this.deliveredToATFField;
            }
            set {
                this.deliveredToATFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveredToAE")]
        public SchemeReturnDeliveredToAE[] DeliveredToAE {
            get {
                return this.deliveredToAEField;
            }
            set {
                this.deliveredToAEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Return", IsNullable=false)]
        public TonnageReturnType[] B2CWEEEFromDistributors {
            get {
                return this.b2CWEEEFromDistributorsField;
            }
            set {
                this.b2CWEEEFromDistributorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Return", IsNullable=false)]
        public TonnageReturnType[] B2CWEEEFromFinalHolders {
            get {
                return this.b2CWEEEFromFinalHoldersField;
            }
            set {
                this.b2CWEEEFromFinalHoldersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Producer", IsNullable=false)]
        public SchemeReturnProducer[] ProducerList {
            get {
                return this.producerListField;
            }
            set {
                this.producerListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public enum SchemeReturnReturnPeriod {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Quarter 1: January - March")]
        Quarter1JanuaryMarch,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Quarter 2: April - June")]
        Quarter2AprilJune,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Quarter 3: July - September")]
        Quarter3JulySeptember,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Quarter 4: October - December")]
        Quarter4OctoberDecember,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public partial class TonnageReturnType {
        
        private categoryNameType categoryNameField;
        
        private obligationTypeType obligationTypeField;
        
        private decimal tonnesReturnValueField;
        
        /// <remarks/>
        public categoryNameType CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        public obligationTypeType ObligationType {
            get {
                return this.obligationTypeField;
            }
            set {
                this.obligationTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal TonnesReturnValue {
            get {
                return this.tonnesReturnValueField;
            }
            set {
                this.tonnesReturnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public enum categoryNameType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Large Household Appliances")]
        LargeHouseholdAppliances,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Small Household Appliances")]
        SmallHouseholdAppliances,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IT and Telecomms Equipment")]
        ITandTelecommsEquipment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Consumer Equipment")]
        ConsumerEquipment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Lighting Equipment")]
        LightingEquipment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Electrical and Electronic Tools")]
        ElectricalandElectronicTools,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Toys Leisure and Sports")]
        ToysLeisureandSports,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Medical Devices")]
        MedicalDevices,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Monitoring and Control Instruments")]
        MonitoringandControlInstruments,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automatic Dispensers")]
        AutomaticDispensers,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Display Equipment")]
        DisplayEquipment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Cooling Appliances Containing Refrigerants")]
        CoolingAppliancesContainingRefrigerants,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Gas Discharge Lamps and LED light sources")]
        GasDischargeLampsandLEDlightsources,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Photovoltaic Panels")]
        PhotovoltaicPanels,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public enum obligationTypeType {
        
        /// <remarks/>
        B2B,
        
        /// <remarks/>
        B2C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public partial class SchemeReturnDeliveredToATF {
        
        private SchemeReturnDeliveredToATFDeliveredToFacility deliveredToFacilityField;
        
        private TonnageReturnType[] returnField;
        
        /// <remarks/>
        public SchemeReturnDeliveredToATFDeliveredToFacility DeliveredToFacility {
            get {
                return this.deliveredToFacilityField;
            }
            set {
                this.deliveredToFacilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Return")]
        public TonnageReturnType[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public partial class SchemeReturnDeliveredToATFDeliveredToFacility {
        
        private string aATFApprovalNoField;
        
        private string facilityNameField;
        
        /// <remarks/>
        public string AATFApprovalNo {
            get {
                return this.aATFApprovalNoField;
            }
            set {
                this.aATFApprovalNoField = value;
            }
        }
        
        /// <remarks/>
        public string FacilityName {
            get {
                return this.facilityNameField;
            }
            set {
                this.facilityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public partial class SchemeReturnDeliveredToAE {
        
        private SchemeReturnDeliveredToAEDeliveredToOperator deliveredToOperatorField;
        
        private TonnageReturnType[] returnField;
        
        /// <remarks/>
        public SchemeReturnDeliveredToAEDeliveredToOperator DeliveredToOperator {
            get {
                return this.deliveredToOperatorField;
            }
            set {
                this.deliveredToOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Return")]
        public TonnageReturnType[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public partial class SchemeReturnDeliveredToAEDeliveredToOperator {
        
        private string aEApprovalNoField;
        
        private string operatorNameField;
        
        /// <remarks/>
        public string AEApprovalNo {
            get {
                return this.aEApprovalNoField;
            }
            set {
                this.aEApprovalNoField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.environment-agency.gov.uk/WEEE/XMLSchema/SchemeReturns")]
    public partial class SchemeReturnProducer {
        
        private string registrationNoField;
        
        private string producerCompanyNameField;
        
        private TonnageReturnType[] returnField;
        
        /// <remarks/>
        public string RegistrationNo {
            get {
                return this.registrationNoField;
            }
            set {
                this.registrationNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string ProducerCompanyName {
            get {
                return this.producerCompanyNameField;
            }
            set {
                this.producerCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Return")]
        public TonnageReturnType[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
}
