//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AatfDeliveryLocation
    {
        public AatfDeliveryLocation()
        {
            this.WeeeDeliveredAmounts = new HashSet<WeeeDeliveredAmount>();
        }
    
        public System.Guid Id { get; set; }
        public string ApprovalNumber { get; set; }
        public string FacilityName { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<WeeeDeliveredAmount> WeeeDeliveredAmounts { get; set; }
    }
}
