//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AATFReturn
    {
        public AATFReturn()
        {
            this.AATFReturnReportOns = new HashSet<AATFReturnReportOn>();
            this.AATFReturnSchemes = new HashSet<AATFReturnScheme>();
            this.WeeeReceiveds = new HashSet<WeeeReceived>();
            this.WeeeReuseds = new HashSet<WeeeReused>();
            this.WeeeSentOns = new HashSet<WeeeSentOn>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ReturnId { get; set; }
        public System.Guid AATFId { get; set; }
    
        public virtual AATF AATF { get; set; }
        public virtual Return Return { get; set; }
        public virtual ICollection<AATFReturnReportOn> AATFReturnReportOns { get; set; }
        public virtual ICollection<AATFReturnScheme> AATFReturnSchemes { get; set; }
        public virtual ICollection<WeeeReceived> WeeeReceiveds { get; set; }
        public virtual ICollection<WeeeReused> WeeeReuseds { get; set; }
        public virtual ICollection<WeeeSentOn> WeeeSentOns { get; set; }
    }
}
