//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AATF
    {
        public AATF()
        {
            this.AATFReturns = new HashSet<AATFReturn>();
            this.OperatorAATFs = new HashSet<OperatorAATF>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CompetentAuthorityId { get; set; }
        public string ApprovalNumber { get; set; }
        public string Status { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<AATFReturn> AATFReturns { get; set; }
        public virtual ICollection<OperatorAATF> OperatorAATFs { get; set; }
    }
}
