//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System.Collections.Generic;

    public partial class Address
    {
        public Address()
        {
            this.Organisations = new HashSet<Organisation>();
            this.Organisations1 = new HashSet<Organisation>();
            this.Organisations2 = new HashSet<Organisation>();
        }
    
        public System.Guid Id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TownOrCity { get; set; }
        public string CountyOrRegion { get; set; }
        public string Postcode { get; set; }
        public System.Guid CountryId { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Organisation> Organisations { get; set; }
        public virtual ICollection<Organisation> Organisations1 { get; set; }
        public virtual ICollection<Organisation> Organisations2 { get; set; }
    }
}
