//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.CompetentAuthorityUsers = new HashSet<CompetentAuthorityUser>();
            this.OrganisationUsers = new HashSet<OrganisationUser>();
            this.MemberUploads = new HashSet<MemberUpload>();
            this.MemberUploads1 = new HashSet<MemberUpload>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<CompetentAuthorityUser> CompetentAuthorityUsers { get; set; }
        public virtual ICollection<OrganisationUser> OrganisationUsers { get; set; }
        public virtual ICollection<MemberUpload> MemberUploads { get; set; }
        public virtual ICollection<MemberUpload> MemberUploads1 { get; set; }
    }
}
