//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System.Collections.Generic;

    public partial class ChargeBandAmount
    {
        public ChargeBandAmount()
        {
            this.Producers = new HashSet<Producer>();
        }
    
        public System.Guid Id { get; set; }
        public decimal Amount { get; set; }
        public int ChargeBand { get; set; }
    
        public virtual ICollection<Producer> Producers { get; set; }
    }
}
