//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact1
    {
        public Contact1()
        {
            this.AuthorisedRepresentatives = new HashSet<AuthorisedRepresentative>();
            this.Businesses = new HashSet<Business>();
            this.Companies = new HashSet<Company>();
            this.Partnerships = new HashSet<Partnership>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Title { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public System.Guid AddressId { get; set; }
    
        public virtual Address1 Address1 { get; set; }
        public virtual ICollection<AuthorisedRepresentative> AuthorisedRepresentatives { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Partnership> Partnerships { get; set; }
    }
}
