//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System.Collections.Generic;

    public partial class Country
    {
        public Country()
        {
            this.CompetentAuthorities = new HashSet<CompetentAuthority>();
            this.Addresses = new HashSet<Address>();
            this.Address1 = new HashSet<Address1>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CompetentAuthority> CompetentAuthorities { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Address1> Address1 { get; set; }
    }
}
