//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataReturn
    {
        public DataReturn()
        {
            this.DataReturnVersions = new HashSet<DataReturnVersion>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int ComplianceYear { get; set; }
        public System.Guid SchemeId { get; set; }
        public Nullable<System.Guid> CurrentDataReturnVersionId { get; set; }
        public int Quarter { get; set; }
    
        public virtual DataReturnVersion CurrentDataReturnVersion { get; set; }
        public virtual Scheme Scheme { get; set; }
        public virtual ICollection<DataReturnVersion> DataReturnVersions { get; set; }
    }
}
