//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataReturnUpload
    {
        public DataReturnUpload()
        {
            this.DataReturnUploadErrors = new HashSet<DataReturnUploadError>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Data { get; set; }
        public System.DateTime Date { get; set; }
        public string FileName { get; set; }
        public System.Guid SchemeId { get; set; }
        public Nullable<int> ComplianceYear { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<System.Guid> DataReturnVersionId { get; set; }
        public System.TimeSpan ProcessTime { get; set; }
    
        public virtual DataReturnVersion DataReturnVersion { get; set; }
        public virtual Scheme Scheme { get; set; }
        public virtual ICollection<DataReturnUploadError> DataReturnUploadErrors { get; set; }
    }
}
