//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IbisFileData
    {
        public IbisFileData()
        {
            this.InvoiceRuns = new HashSet<InvoiceRun>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public long FileId { get; set; }
        public string CustomerFileName { get; set; }
        public string CustomerFileData { get; set; }
        public string TransactionFileName { get; set; }
        public string TransactionFileData { get; set; }
    
        public virtual ICollection<InvoiceRun> InvoiceRuns { get; set; }
    }
}
