//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRun
    {
        public InvoiceRun()
        {
            this.MemberUploads = new HashSet<MemberUpload>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid CompetentAuthorityId { get; set; }
        public Nullable<System.Guid> IbisFileDataId { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedByUserId { get; set; }
    
        public virtual IbisFileData IbisFileData { get; set; }
        public virtual CompetentAuthority CompetentAuthority { get; set; }
        public virtual ICollection<MemberUpload> MemberUploads { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
