//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigratedProducer_
    {
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string ProducerRegistrationNumber { get; set; }
        public string ProducerName { get; set; }
        public string CompanyNumber { get; set; }
    }
}
