//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompetentAuthorityUser> CompetentAuthorityUsers { get; set; }
        public virtual DbSet<CompetentAuthority> CompetentAuthorities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<OrganisationUser> OrganisationUsers { get; set; }
        public virtual DbSet<MemberUpload> MemberUploads { get; set; }
        public virtual DbSet<MemberUploadError> MemberUploadErrors { get; set; }
        public virtual DbSet<Scheme> Schemes { get; set; }
        public virtual DbSet<Address1> Address1 { get; set; }
        public virtual DbSet<AuthorisedRepresentative> AuthorisedRepresentatives { get; set; }
        public virtual DbSet<BrandName_> BrandName_Set { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact1> Contact1 { get; set; }
        public virtual DbSet<MigratedProducer_> MigratedProducer_Set { get; set; }
        public virtual DbSet<Partner_> Partner_Set { get; set; }
        public virtual DbSet<Partnership> Partnerships { get; set; }
        public virtual DbSet<SICCode_> SICCode_Set { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ChargeBandAmount> ChargeBandAmounts { get; set; }
        public virtual DbSet<ProducerSubmission> ProducerSubmissions { get; set; }
        public virtual DbSet<RegisteredProducer> RegisteredProducers { get; set; }
        public virtual DbSet<DataReturn> DataReturns { get; set; }
        public virtual DbSet<DataReturnUpload> DataReturnUploads { get; set; }
        public virtual DbSet<DataReturnUploadError> DataReturnUploadErrors { get; set; }
        public virtual DbSet<DataReturnVersion> DataReturnVersions { get; set; }
        public virtual DbSet<EeeOutputAmount> EeeOutputAmounts { get; set; }
        public virtual DbSet<EeeOutputReturnVersion> EeeOutputReturnVersions { get; set; }
        public virtual DbSet<WeeeCollectedAmount> WeeeCollectedAmounts { get; set; }
        public virtual DbSet<WeeeCollectedReturnVersion> WeeeCollectedReturnVersions { get; set; }
        public virtual DbSet<WeeeDeliveredAmount> WeeeDeliveredAmounts { get; set; }
        public virtual DbSet<WeeeDeliveredReturnVersion> WeeeDeliveredReturnVersions { get; set; }
        public virtual DbSet<EeeOutputReturnVersionAmount> EeeOutputReturnVersionAmounts { get; set; }
        public virtual DbSet<WeeeCollectedReturnVersionAmount> WeeeCollectedReturnVersionAmounts { get; set; }
        public virtual DbSet<WeeeDeliveredReturnVersionAmount> WeeeDeliveredReturnVersionAmounts { get; set; }
        public virtual DbSet<AatfDeliveryLocation> AatfDeliveryLocations { get; set; }
        public virtual DbSet<AeDeliveryLocation> AeDeliveryLocations { get; set; }
        public virtual DbSet<IbisFileData> IbisFileDatas { get; set; }
        public virtual DbSet<InvoiceRun> InvoiceRuns { get; set; }
        public virtual DbSet<QuarterWindowTemplate> QuarterWindowTemplates { get; set; }
    }
}
