//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public Operator()
        {
            this.Returns = new HashSet<Return>();
            this.AATFs = new HashSet<AATF>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrganisationId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<Return> Returns { get; set; }
        public virtual ICollection<AATF> AATFs { get; set; }
    }
}
