//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorAATF
    {
        public System.Guid Id { get; set; }
        public System.Guid OperatorId { get; set; }
        public System.Guid AATFId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual AATF AATF { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
