//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterWindowTemplate
    {
        public System.Guid Id { get; set; }
        public int Quarter { get; set; }
        public int AddStartYears { get; set; }
        public int StartMonth { get; set; }
        public int StartDay { get; set; }
        public int AddEndYears { get; set; }
        public int EndMonth { get; set; }
        public int EndDay { get; set; }
    }
}
