//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheme
    {
        public Scheme()
        {
            this.MemberUploads = new HashSet<MemberUpload>();
            this.RegisteredProducers = new HashSet<RegisteredProducer>();
            this.DataReturns = new HashSet<DataReturn>();
            this.DataReturnUploads = new HashSet<DataReturnUpload>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int SchemeStatus { get; set; }
        public string ApprovalNumber { get; set; }
        public System.Guid OrganisationId { get; set; }
        public string SchemeName { get; set; }
        public string IbisCustomerReference { get; set; }
        public Nullable<int> ObligationType { get; set; }
        public Nullable<System.Guid> CompetentAuthorityId { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<MemberUpload> MemberUploads { get; set; }
        public virtual ICollection<RegisteredProducer> RegisteredProducers { get; set; }
        public virtual ICollection<DataReturn> DataReturns { get; set; }
        public virtual ICollection<DataReturnUpload> DataReturnUploads { get; set; }
    }
}
