//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{

    public partial class SICCode_
    {
        public System.Guid Id { get; set; }
        public System.Guid ProducerId { get; set; }
        public string Name { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Producer Producer { get; set; }
    }
}
