//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeeSentOn
    {
        public WeeeSentOn()
        {
            this.WeeeSentOnAmounts = new HashSet<WeeeSentOnAmount>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid SiteAddressId { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid ReturnId { get; set; }
        public System.Guid AatfId { get; set; }
        public Nullable<System.Guid> OperatorAddressId { get; set; }
    
        public virtual Return Return { get; set; }
        public virtual ICollection<WeeeSentOnAmount> WeeeSentOnAmounts { get; set; }
        public virtual AATF AATF { get; set; }
    }
}
