//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeeReused
    {
        public WeeeReused()
        {
            this.WeeeReusedAmounts = new HashSet<WeeeReusedAmount>();
            this.WeeeReusedSites = new HashSet<WeeeReusedSite>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RowVersion { get; set; }
        public System.Guid ReturnId { get; set; }
        public System.Guid AatfId { get; set; }
    
        public virtual ICollection<WeeeReusedAmount> WeeeReusedAmounts { get; set; }
        public virtual ICollection<WeeeReusedSite> WeeeReusedSites { get; set; }
        public virtual Return Return { get; set; }
        public virtual AATF AATF { get; set; }
    }
}
