//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeeCollectedAmount
    {
        public WeeeCollectedAmount()
        {
            this.WeeeCollectedReturnVersionAmounts = new HashSet<WeeeCollectedReturnVersionAmount>();
        }
    
        public System.Guid Id { get; set; }
        public int SourceType { get; set; }
        public System.Guid WeeeCategoryId { get; set; }
        public string ObligationType { get; set; }
        public decimal Tonnage { get; set; }
    
        public virtual WeeeCategory WeeeCategory { get; set; }
        public virtual ICollection<WeeeCollectedReturnVersionAmount> WeeeCollectedReturnVersionAmounts { get; set; }
    }
}
