//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeeCollectedReturnVersionAmount
    {
        public System.Guid WeeeCollectedReturnVersionId { get; set; }
        public System.Guid WeeeCollectedAmountId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual WeeeCollectedAmount WeeeCollectedAmount { get; set; }
        public virtual WeeeCollectedReturnVersion WeeeCollectedReturnVersion { get; set; }
    }
}
