//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.Weee.Tests.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeeDeliveredAmount
    {
        public WeeeDeliveredAmount()
        {
            this.WeeeDeliveredReturnVersionAmounts = new HashSet<WeeeDeliveredReturnVersionAmount>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AatfDeliveryLocationId { get; set; }
        public Nullable<System.Guid> AeDeliveryLocationId { get; set; }
        public System.Guid WeeeCategoryId { get; set; }
        public string ObligationType { get; set; }
        public decimal Tonnage { get; set; }
    
        public virtual WeeeCategory WeeeCategory { get; set; }
        public virtual AatfDeliveryLocation AatfDeliveryLocation { get; set; }
        public virtual AeDeliveryLocation AeDeliveryLocation { get; set; }
        public virtual ICollection<WeeeDeliveredReturnVersionAmount> WeeeDeliveredReturnVersionAmounts { get; set; }
    }
}
