//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.AatfReturn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Weee.Web.Areas.AatfReturn.Views.App_LocalResources.ReturnsResources", typeof(ReturnsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AATF approval number.
        /// </summary>
        public static string AATFApprovalNumber {
            get {
                return ResourceManager.GetString("AATFApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AATF / ATF name and address.
        /// </summary>
        public static string AATFATFnameAndAddress {
            get {
                return ResourceManager.GetString("AATFATFnameAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AATF name and address.
        /// </summary>
        public static string AATFNameAndAddress {
            get {
                return ResourceManager.GetString("AATFNameAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add / edit data.
        /// </summary>
        public static string AddEditData {
            get {
                return ResourceManager.GetString("AddEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval number.
        /// </summary>
        public static string ApprovalNumber {
            get {
                return ResourceManager.GetString("ApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B (tonnes).
        /// </summary>
        public static string B2B {
            get {
                return ResourceManager.GetString("B2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2C (tonnes).
        /// </summary>
        public static string B2C {
            get {
                return ResourceManager.GetString("B2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown by PCS.
        /// </summary>
        public static string BreakDownByPcs {
            get {
                return ResourceManager.GetString("BreakDownByPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance month and year.
        /// </summary>
        public static string ComplianceYearAndMonth {
            get {
                return ResourceManager.GetString("ComplianceYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit details.
        /// </summary>
        public static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tonnage.
        /// </summary>
        public static string EditTonnage {
            get {
                return ResourceManager.GetString("EditTonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kept / retained by a DCF.
        /// </summary>
        public static string KeptRetainedByDcf {
            get {
                return ResourceManager.GetString("KeptRetainedByDcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-obligated WEEE.
        /// </summary>
        public static string NonObligatedWeee {
            get {
                return ResourceManager.GetString("NonObligatedWeee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to report.
        /// </summary>
        public static string NothingToReport {
            get {
                return ResourceManager.GetString("NothingToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected for reporting this quarter.
        /// </summary>
        public static string NotSelectedForReporting {
            get {
                return ResourceManager.GetString("NotSelectedForReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligated WEEE.
        /// </summary>
        public static string ObligatedWeee {
            get {
                return ResourceManager.GetString("ObligatedWeee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator name and address.
        /// </summary>
        public static string OperatorNameAndAddress {
            get {
                return ResourceManager.GetString("OperatorNameAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS name.
        /// </summary>
        public static string PCSName {
            get {
                return ResourceManager.GetString("PCSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received on behalf of PCS(s).
        /// </summary>
        public static string ReceivedOnBehalfOfPcs {
            get {
                return ResourceManager.GetString("ReceivedOnBehalfOfPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report data.
        /// </summary>
        public static string ReportData {
            get {
                return ResourceManager.GetString("ReportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting on.
        /// </summary>
        public static string ReportingOn {
            get {
                return ResourceManager.GetString("ReportingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reused as a whole appliance.
        /// </summary>
        public static string ReusedAsWholeAppliance {
            get {
                return ResourceManager.GetString("ReusedAsWholeAppliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to another AATF / ATF.
        /// </summary>
        public static string SentToAnotherAatf {
            get {
                return ResourceManager.GetString("SentToAnotherAatf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (tonnes).
        /// </summary>
        public static string TotalTonnes {
            get {
                return ResourceManager.GetString("TotalTonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEE sent B2B (tonnes).
        /// </summary>
        public static string WEEESentB2B {
            get {
                return ResourceManager.GetString("WEEESentB2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEE sent B2C (tonnes).
        /// </summary>
        public static string WEEESentB2C {
            get {
                return ResourceManager.GetString("WEEESentB2C", resourceCulture);
            }
        }
    }
}
