//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.AatfReturn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EA.Weee.Web.Areas.AatfReturn.Views.App_LocalResources.ReturnsResources", typeof(ReturnsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AATF approval number.
        /// </summary>
        public static string AATFApprovalNumber {
            get {
                return ResourceManager.GetString("AATFApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AATF / ATF name and address.
        /// </summary>
        public static string AATFATFnameAndAddress {
            get {
                return ResourceManager.GetString("AATFATFnameAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AATF name and address.
        /// </summary>
        public static string AATFNameAndAddress {
            get {
                return ResourceManager.GetString("AATFNameAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an AATF.
        /// </summary>
        public static string AddAnAATF {
            get {
                return ResourceManager.GetString("AddAnAATF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an ATF.
        /// </summary>
        public static string AddAnATF {
            get {
                return ResourceManager.GetString("AddAnATF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add / edit data.
        /// </summary>
        public static string AddEditData {
            get {
                return ResourceManager.GetString("AddEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval number.
        /// </summary>
        public static string ApprovalNumber {
            get {
                return ResourceManager.GetString("ApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B (tonnes).
        /// </summary>
        public static string B2B {
            get {
                return ResourceManager.GetString("B2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2C (tonnes).
        /// </summary>
        public static string B2C {
            get {
                return ResourceManager.GetString("B2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown by PCS.
        /// </summary>
        public static string BreakDownByPcs {
            get {
                return ResourceManager.GetString("BreakDownByPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string CapitalisedActions {
            get {
                return ResourceManager.GetString("CapitalisedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all breakdown by PCS.
        /// </summary>
        public static string CloseAllPcs {
            get {
                return ResourceManager.GetString("CloseAllPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance month and year.
        /// </summary>
        public static string ComplianceYearAndMonth {
            get {
                return ResourceManager.GetString("ComplianceYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the difference between an AATF and an ATF?.
        /// </summary>
        public static string DifferenceAnAATFAndATF {
            get {
                return ResourceManager.GetString("DifferenceAnAATFAndATF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit details.
        /// </summary>
        public static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tonnage.
        /// </summary>
        public static string EditTonnage {
            get {
                return ResourceManager.GetString("EditTonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kept / retained by a DCF.
        /// </summary>
        public static string KeptRetainedByDcf {
            get {
                return ResourceManager.GetString("KeptRetainedByDcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-obligated WEEE.
        /// </summary>
        public static string NonObligatedWeee {
            get {
                return ResourceManager.GetString("NonObligatedWeee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to report.
        /// </summary>
        public static string NothingToReport {
            get {
                return ResourceManager.GetString("NothingToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected for reporting this quarter.
        /// </summary>
        public static string NotSelectedForReporting {
            get {
                return ResourceManager.GetString("NotSelectedForReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligated WEEE.
        /// </summary>
        public static string ObligatedWeee {
            get {
                return ResourceManager.GetString("ObligatedWeee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open all breakdown by PCS.
        /// </summary>
        public static string OpenAllPcs {
            get {
                return ResourceManager.GetString("OpenAllPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator name and address.
        /// </summary>
        public static string OperatorNameAndAddress {
            get {
                return ResourceManager.GetString("OperatorNameAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCS name.
        /// </summary>
        public static string PCSName {
            get {
                return ResourceManager.GetString("PCSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received on behalf of PCS(s).
        /// </summary>
        public static string ReceivedOnBehalfOfPcs {
            get {
                return ResourceManager.GetString("ReceivedOnBehalfOfPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this AATF / ATF from your list?.
        /// </summary>
        public static string RemoveAATFATFConfirmTitle {
            get {
                return ResourceManager.GetString("RemoveAATFATFConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove AATF / ATF from your list.
        /// </summary>
        public static string RemoveAATFATFfromyourlist {
            get {
                return ResourceManager.GetString("RemoveAATFATFfromyourlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing this AATF / ATF will delete all tonnage data associated with it.
        /// </summary>
        public static string RemoveAATFATFMsg {
            get {
                return ResourceManager.GetString("RemoveAATFATFMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report data.
        /// </summary>
        public static string ReportData {
            get {
                return ResourceManager.GetString("ReportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting on.
        /// </summary>
        public static string ReportingOn {
            get {
                return ResourceManager.GetString("ReportingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reused as a whole appliance.
        /// </summary>
        public static string ReusedAsWholeAppliance {
            get {
                return ResourceManager.GetString("ReusedAsWholeAppliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for the AATF by name, operator name or approval number.
        /// </summary>
        public static string SearchAnAATFByNameInfo {
            get {
                return ResourceManager.GetString("SearchAnAATFByNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the treatment facility where WEEE was sent to.
        /// </summary>
        public static string SearchAnAATFHeading {
            get {
                return ResourceManager.GetString("SearchAnAATFHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A treatment facility where WEEE was sent on to can be an AATF or an ATF (an ATF is an authorised treatment facility that is not approved to issue evidence)..
        /// </summary>
        public static string SearchAnAATFHeadingInfo {
            get {
                return ResourceManager.GetString("SearchAnAATFHeadingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the search to find and add an AATF for this compliance year. If you are unsure if the treatment facility is an AATF or ATF, perform a search..
        /// </summary>
        public static string SearchAnAATFInfo {
            get {
                return ResourceManager.GetString("SearchAnAATFInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you know the treatment facility is an ATF, use the link to add it. If you are unsure if the treatment facility is an ATF or an AATF, perform a search..
        /// </summary>
        public static string SearchAnATFInfo {
            get {
                return ResourceManager.GetString("SearchAnATFInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to another AATF / ATF.
        /// </summary>
        public static string SentToAnotherAatf {
            get {
                return ResourceManager.GetString("SentToAnotherAatf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (tonnes).
        /// </summary>
        public static string TotalTonnes {
            get {
                return ResourceManager.GetString("TotalTonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total WEEE that has been reused.
        /// </summary>
        public static string TotalWeeeReusedTableCaption {
            get {
                return ResourceManager.GetString("TotalWeeeReusedTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of address.
        /// </summary>
        public static string Typeofaddress {
            get {
                return ResourceManager.GetString("Typeofaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is WEEE that has been refurbished or repaired to the point it is no longer waste.
        /// </summary>
        public static string WeeeReusedDescription {
            get {
                return ResourceManager.GetString("WeeeReusedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEE that has been reused sites.
        /// </summary>
        public static string WeeeReusedSitesTableCaption {
            get {
                return ResourceManager.GetString("WeeeReusedSitesTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEE sent B2B (tonnes).
        /// </summary>
        public static string WEEESentB2B {
            get {
                return ResourceManager.GetString("WEEESentB2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEE sent B2C (tonnes).
        /// </summary>
        public static string WEEESentB2C {
            get {
                return ResourceManager.GetString("WEEESentB2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEEE sent on.
        /// </summary>
        public static string WEEESentOn {
            get {
                return ResourceManager.GetString("WEEESentOn", resourceCulture);
            }
        }
    }
}
