CREATE TABLE [AATF].[ReturnAatf] (
    [Id]	UNIQUEIDENTIFIER NOT NULL,
    [ReturnId]	UNIQUEIDENTIFIER NOT NULL,
	[AatfId]	UNIQUEIDENTIFIER NOT NULL

    CONSTRAINT [PK_ReturnAatf_Id] PRIMARY KEY CLUSTERED ([Id] ASC)
);

ALTER TABLE [AATF].[ReturnAatf] WITH NOCHECK
    ADD CONSTRAINT [FK_ReturnAatf_Return] FOREIGN KEY ([ReturnId]) REFERENCES [AATF].[Return] ([Id]);

ALTER TABLE [AATF].[ReturnAatf] WITH NOCHECK
    ADD CONSTRAINT [FK_ReturnAatf_Aatf] FOREIGN KEY ([AatfId]) REFERENCES [AATF].[Aatf] ([Id]);
GO
ALTER TABLE [AATF].[ReturnAatf]
    ADD [RowVersion] ROWVERSION NOT NULL;

GO