ALTER TABLE [AATF].AATF ADD ContactId uniqueidentifier NULL;
ALTER TABLE [AATF].AATF ADD CONSTRAINT FK_Aatf_Contact_ContactId FOREIGN KEY (ContactId) REFERENCES [AATF].[Contact](Id);
GO

ALTER TABLE [AATF].AATF ALTER COLUMN ContactId uniqueidentifier NOT NULL;
GO