
GO
PRINT N'Altering [Lookup].[Country]...';

INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Afghanistan','AF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Åland Islands','AX',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Albania','AL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Algeria','DZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'American Samoa','AS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Andorra','AD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Angola','AO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Anguilla','AI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Antarctica','AQ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Antigua and Barbuda','AG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Argentina','AR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Armenia','AM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Aruba','AW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Australia','AU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Austria','AT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Azerbaijan','AZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bahamas','BS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bahrain','BH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bangladesh','BD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Barbados','BB',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Belarus','BY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Belgium','BE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Belize','BZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Benin','BJ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bermuda','BM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bhutan','BT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bolivia','BO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bosnia and Herzegovina','BA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Botswana','BW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bouvet Island','BV',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Brazil','BR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'British Indian Ocean Territory','IO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Brunei Darussalam','BN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Bulgaria','BG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Burkina Faso','BF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Burundi','BI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cambodia','KH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cameroon','CM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Canada','CA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cape Verde','CV',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Caribbean Netherlands ','BQ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cayman Islands','KY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Central African Republic','CF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Chad','TD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Chile','CL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'China','CN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Christmas Island','CX',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cocos (Keeling) Islands','CC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Colombia','CO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Comoros','KM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Congo','CG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Congo, Democratic Republic of','CD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cook Islands','CK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Costa Rica','CR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Côte d''Ivoire','CI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Croatia','HR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cuba','CU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Curaçao','CW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Cyprus','CY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Czech Republic','CZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Denmark','DK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Djibouti','DJ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Dominica','DM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Dominican Republic','DO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Ecuador','EC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Egypt','EG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'El Salvador','SV',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Equatorial Guinea','GQ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Eritrea','ER',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Estonia','EE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Ethiopia','ET',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Falkland Islands','FK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Faroe Islands','FO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Fiji','FJ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Finland','FI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'France','FR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'French Guiana','GF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'French Polynesia','PF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'French Southern Territories','TF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Gabon','GA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Gambia','GM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Georgia','GE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Germany','DE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Ghana','GH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Gibraltar','GI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Greece','GR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Greenland','GL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Grenada','GD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guadeloupe','GP',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guam','GU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guatemala','GT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guernsey','GG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guinea','GN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guinea-Bissau','GW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Guyana','GY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Haiti','HT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Heard and McDonald Islands','HM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Honduras','HN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Hong Kong','HK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Hungary','HU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Iceland','IS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'India','IN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Indonesia','ID',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Iran','IR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Iraq','IQ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Ireland','IE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Isle of Man','IM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Israel','IL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Italy','IT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Jamaica','JM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Japan','JP',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Jersey','JE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Jordan','JO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Kazakhstan','KZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Kenya','KE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Kiribati','KI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Kuwait','KW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Kyrgyzstan','KG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Lao People''s Democratic Republic','LA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Latvia','LV',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Lebanon','LB',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Lesotho','LS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Liberia','LR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Libya','LY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Liechtenstein','LI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Lithuania','LT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Luxembourg','LU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Macau','MO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Macedonia','MK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Madagascar','MG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Malawi','MW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Malaysia','MY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Maldives','MV',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mali','ML',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Malta','MT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Marshall Islands','MH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Martinique','MQ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mauritania','MR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mauritius','MU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mayotte','YT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mexico','MX',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Micronesia, Federated States of','FM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Moldova','MD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Monaco','MC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mongolia','MN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Montenegro','ME',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Montserrat','MS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Morocco','MA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Mozambique','MZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Myanmar','MM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Namibia','NA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Nauru','NR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Nepal','NP',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'New Caledonia','NC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'New Zealand','NZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Nicaragua','NI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Niger','NE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Nigeria','NG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Niue','NU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Norfolk Island','NF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'North Korea','KP',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Northern Mariana Islands','MP',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Norway','NO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Oman','OM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Pakistan','PK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Palau','PW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Palestine, State of','PS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Panama','PA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Papua New Guinea','PG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Paraguay','PY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Peru','PE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Philippines','PH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Pitcairn','PN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Poland','PL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Portugal','PT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Puerto Rico','PR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Qatar','QA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Réunion','RE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Romania','RO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Russian Federation','RU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Rwanda','RW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saint Barthélemy','BL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saint Helena','SH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saint Kitts and Nevis','KN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saint Lucia','LC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saint Vincent and the Grenadines','VC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saint-Martin (France)','MF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Samoa','WS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'San Marino','SM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Sao Tome and Principe','ST',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Saudi Arabia','SA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Senegal','SN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Serbia','RS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Seychelles','SC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Sierra Leone','SL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Singapore','SG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Sint Maarten (Dutch part)','SX',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Slovakia','SK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Slovenia','SI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Solomon Islands','SB',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Somalia','SO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'South Africa','ZA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'South Georgia and the South Sandwich Islands','GS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'South Korea','KR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'South Sudan','SS',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Spain','ES',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Sri Lanka','LK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'St. Pierre and Miquelon','PM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Sudan','SD',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Suriname','SR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Svalbard and Jan Mayen Islands','SJ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Swaziland','SZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Sweden','SE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Switzerland','CH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Syria','SY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Taiwan','TW',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Tajikistan','TJ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Tanzania','TZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Thailand','TH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'The Netherlands','NL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Timor-Leste','TL',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Togo','TG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Tokelau','TK',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Tonga','TO',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Trinidad and Tobago','TT',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Tunisia','TN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Turkey','TR',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Turkmenistan','TM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Turks and Caicos Islands','TC',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Tuvalu','TV',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Uganda','UG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Ukraine','UA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'United Arab Emirates','AE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'United Kingdom','GB',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'United States','US',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'United States Minor Outlying Islands','UM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Uruguay','UY',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Uzbekistan','UZ',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Vanuatu','VU',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Vatican','VA',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Venezuela','VE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Vietnam','VN',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Virgin Islands (British)','VG',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Virgin Islands (U.S.)','VI',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Wallis and Futuna Islands','WF',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Western Sahara','EH',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Yemen','YE',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Zambia','ZM',0)
INSERT INTO [Lookup].[Country]([Id],[Name],[IsoAlpha2Code],[IsEuropeanUnionMember])VALUES(newid(),'Zimbabwe','ZW',0)


GO
PRINT N'Update complete.';


GO

