
GO
PRINT N'Altering [Lookup].[Country]...';

INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Afghanistan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Åland Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Albania')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Algeria')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'American Samoa')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Andorra')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Angola')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Anguilla')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Antarctica')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Antigua and Barbuda')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Argentina')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Armenia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Aruba')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Australia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Austria')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Azerbaijan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bahamas')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bahrain')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bangladesh')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Barbados')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Belarus')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Belgium')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Belize')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Benin')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bermuda')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bhutan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bolivia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bonaire, Sint Eustatius and Saba')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bosnia and Herzegovina')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Botswana')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bouvet Island')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Brazil')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'British Indian Ocean Territory')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Brunei Darussalam')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Bulgaria')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Burkina Faso')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Burundi')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cabo Verde')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cambodia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cameroon')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Canada')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cayman Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Central African Republic')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Chad')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Chile')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'China')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Christmas Island')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cocos (Keeling) Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Colombia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Comoros')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Congo')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Congo, Democratic Republic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cook Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Costa Rica')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Côte d''Ivoire')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Croatia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cuba')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Curaçao')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Cyprus')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Czech Republic')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Denmark')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Djibouti')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Dominica')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Dominican Republic')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Ecuador')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Egypt')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'El Salvador')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Equatorial Guinea')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Eritrea')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Estonia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Ethiopia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Falkland Islands, the Malvinas')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Faroe Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Fiji')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Finland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'France')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'French Guiana')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'French Polynesia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'French Southern Territories')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Gabon')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Gambia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Georgia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Germany')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Ghana')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Gibraltar')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Greece')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Greenland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Grenada')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guadeloupe')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guam')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guatemala')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guernsey')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guinea')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guinea-Bissau')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Guyana')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Haiti')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Heard Island and McDonald Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Holy See')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Honduras')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Hong Kong')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Hungary')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Iceland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'India')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Indonesia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Iran, Islamic Republic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Iraq')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Ireland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Isle of Man')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Israel')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Italy')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Jamaica')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Japan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Jersey')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Jordan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Kazakhstan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Kenya')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Kiribati')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Korea, the Democratic People''s Republic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Korea, the Republic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Kuwait')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Kyrgyzstan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Lao People''s Democratic Republic')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Latvia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Lebanon')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Lesotho')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Liberia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Libya')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Liechtenstein')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Lithuania')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Luxembourg')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Macau')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Macedonia, the former Yugoslav Republic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Madagascar')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Malawi')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Malaysia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Maldives')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mali')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Malta')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Marshall Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Martinique')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mauritania')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mauritius')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mayotte')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mexico')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Micronesia, Federated States of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Moldova')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Monaco')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mongolia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Montenegro')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Montserrat')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Morocco')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Mozambique')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Myanmar')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Namibia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Nauru')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Nepal')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Netherlands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'New Caledonia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'New Zealand')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Nicaragua')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Niger')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Nigeria')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Niue')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Norfolk Island')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Northern Mariana Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Norway')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Oman')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Pakistan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Palau')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Palestine, State of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Panama')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Papua New Guinea')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Paraguay')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Peru')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Philippines')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Pitcairn')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Poland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Portugal')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Puerto Rico')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Qatar')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Réunion')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Romania')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Russian Federation')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Rwanda')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint Barthélemy')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint Helena, Ascension and Tristan da Cunha')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint Kitts and Nevis')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint Lucia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint-Martin (France)')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint Pierre and Miquelon')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saint Vincent and the Grenadines')

INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Samoa')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'San Marino')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Sao Tome and Principe')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Saudi Arabia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Senegal')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Serbia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Seychelles')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Sierra Leone')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Singapore')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Sint Maarten (Dutch part)')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Slovakia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Slovenia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Solomon Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Somalia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'South Africa')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'South Georgia and the South Sandwich Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'South Sudan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Spain')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Sri Lanka')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Sudan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Suriname')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Svalbard and Jan Mayen Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Swaziland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Sweden')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Switzerland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Syria Arab Republic')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Taiwan (Province of China)')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Tajikistan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Tanzania, United Republic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Thailand')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Timor-Leste')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Togo')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Tokelau')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Tonga')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Trinidad and Tobago')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Tunisia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Turkey')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Turkmenistan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Turks and Caicos Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Tuvalu')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Uganda')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Ukraine')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'United Arab Emirates')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'UK - England')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'UK - Scotland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'UK - Wales')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'UK - Northern Ireland')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'United States of America')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'United States Minor Outlying Islands')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Uruguay')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Uzbekistan')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Vanuatu')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Venezuela (Bolivarian Repulic of')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Viet Nam')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Virgin Islands (British)')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Virgin Islands (U.S.)')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Wallis and Futuna')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Western Sahara')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Yemen')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Zambia')
INSERT INTO [Lookup].[Country]([Id],[Name])VALUES(newid(),'Zimbabwe')


GO
PRINT N'Update complete.';


GO

