ALTER TABLE [AATF].[Return] DROP CONSTRAINT [FK_Return_Operator]
GO
ALTER TABLE [AATF].[Return] DROP COLUMN OperatorId
GO

ALTER TABLE [AATF].[AATF] ADD OrganisationId UNIQUEIDENTIFIER NULL
GO
ALTER TABLE [AATF].[AATF] ADD CONSTRAINT FK_AATF_Organisation FOREIGN KEY (OrganisationId)  REFERENCES [Organisation].[Organisation](Id) 
GO

UPDATE
	a
SET
	a.OrganisationId = o.OrganisationId
FROM
	[AATF].[AATF] a
	INNER JOIN [AATF].[Operator] o ON o.Id = a.OperatorId

ALTER TABLE [AATF].[AATF] ALTER COLUMN OrganisationId UNIQUEIDENTIFIER NOT NULL
GO
ALTER TABLE [AATF].[AATF] DROP CONSTRAINT [FK_AATFOperator_OperatorId]
GO
ALTER TABLE [AATF].[AATF] DROP COLUMN OperatorId
GO
DROP TABLE [AATF].Operator
